//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        public int payment_Id { get; set; }
        public string cardType { get; set; }
        public int CardNumber { get; set; }
        public string ExpiryDate { get; set; }
        public int cvv { get; set; }
        public string nameOnTheCard { get; set; }
        public int totalamount { get; set; }
    }
}
