//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class reservation
    {
        [DisplayName("BOOKING ID")]
        public int reservation_id { get; set; }
        [DisplayName("USER ID")]
        public int user_id { get; set; }
        [DisplayName("SPORT NAME")]
        public int sport_id { get; set; }
        [DisplayName("BOOKING DATE")]
        public System.DateTime datetime { get; set; }

        [DisplayName("NO OF PEOPLE")]
        public int no_of_people { get; set; }
        [DisplayName("PAYMENT STATUS")]
        public string is_payment_done { get; set; }

        [DisplayName("TOTAL AMOUNT")]
        public int totalBookingCost { get; set; }
    }
}
