//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public int sport_id { get; set; }
        public string sport_name { get; set; }
        public string sport_description { get; set; }
        public int sport_rate { get; set; }
        public int currency_id { get; set; }
    }
}
