//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Sport
    {

        public int sport_id { get; set; }
         
        [DisplayName("Sport Name")]
        [Required(ErrorMessage = "Sport name is required")]
        public string sport_name { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "Sport description is required")]
        public string sport_description { get; set; }

        [DisplayName("Cost Per Person")]
        [Required(ErrorMessage = "Cost Per Person is required")]
        public int sport_rate { get; set; }

        [DisplayName("Currency")]
        [Required(ErrorMessage = "Please select currency")]
        public int currency_id { get; set; }
        //public IEnumerable<SelectListItem> currency { get; set; }

    }
}
