//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Sport
    {
        public int sport_id { get; set; }

        [DisplayName("SPORT NAME")]
        [Required(ErrorMessage = "SPORT NAME is required")]
        public string sport_name { get; set; }


        [DisplayName("SPORT DESCRIPTION")]
        [Required(ErrorMessage = "SPORT DESCRIPTION is required")]
        public string sport_description { get; set; }


        [DisplayName("SPORT RATE")]
        [Required(ErrorMessage = "SPORT RATE is required")]
        public int sport_rate { get; set; }


        [DisplayName("CURRENCY ID")]
        [Required(ErrorMessage = "CURRENCY ID is required")]
        public int currency_id { get; set; }

    }
}
