//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDevelopmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [Required(ErrorMessage = "Name is required")]
        [DisplayName("Full Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [DisplayName("User Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Phone number is required")]
        public string phone { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required")]
        public string password { get; set; }
        public int user_id { get; set; }
        public int is_admin { get; set; }
    }
}
